# Generated by Django 4.1.3 on 2022-11-20 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('hash', models.CharField(max_length=60)),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=8)),
            ],
        ),
    ]
